apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggen-json
spec:
  selector:
    matchLabels:
      app: loggen-json
  replicas: 5
  template:
    metadata:
      labels:
        app: loggen-json
        log_format: json
    spec:
      containers:
        - name: main
          image: sikalabs/slu:v0.66.0
          command:
            - /bin/sh
            - -c
            - exec slu loggen --json --sleep-time 500
          resources:
            requests:
              cpu: 30m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 50Mi
