apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-server-with-metrics-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-06-08-microcomp-kubernetes-example.git
    targetRevision: HEAD
    path: charts/example-metrics
    helm:
      releaseName: example-server-with-metrics-metrics
