apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostpath-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: hostpath-provisioner
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    repoURL: https://charts.rimusz.net
    chart: hostpath-provisioner
    targetRevision: 0.2.13
    helm:
      releaseName: hostpath-provisioner
