apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.10
    helm:
      releaseName: loki
      values: |
        loki:
          isDefault: false
