apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    repoURL: https://helm.mattermost.com
    chart: mattermost-team-edition
    targetRevision: 6.6.26
    helm:
      releaseName: mattermost
      values: |
        # https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-team-edition/values.yaml
        ingress:
          enabled: true
          path: /
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - mattermost.sikademo3.uk
          tls:
            - secretName: mattermost.sikademo3.uk-tls
              hosts:
                - mattermost.sikademo3.uk
        mysql:
          mysqlRootPassword: "asdfasdf"
          mysqlUser: "mm"
          mysqlPassword: "asdfasdf"
        persistence:
          data:
            enabled: true
            size: 10Gi
            accessMode: ReadWriteOnce
          plugins:
            enabled: true
            size: 1Gi
            accessMode: ReadWriteOnce

